package ai.www.mygreendao.example;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COINS".
*/
public class CoinsDao extends AbstractDao<Coins, Long> {

    public static final String TABLENAME = "COINS";

    /**
     * Properties of entity Coins.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CoinId = new Property(1, int.class, "coinId", false, "COIN_ID");
        public final static Property ShortName = new Property(2, String.class, "shortName", false, "shortName");
        public final static Property ChongzhiAddress = new Property(3, String.class, "chongzhiAddress", false, "chongzhiAddress");
    }


    public CoinsDao(DaoConfig config) {
        super(config);
    }
    
    public CoinsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COINS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"COIN_ID\" INTEGER NOT NULL UNIQUE ," + // 1: coinId
                "\"shortName\" TEXT," + // 2: shortName
                "\"chongzhiAddress\" TEXT);"); // 3: chongzhiAddress
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COINS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Coins entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCoinId());
 
        String shortName = entity.getShortName();
        if (shortName != null) {
            stmt.bindString(3, shortName);
        }
 
        String chongzhiAddress = entity.getChongzhiAddress();
        if (chongzhiAddress != null) {
            stmt.bindString(4, chongzhiAddress);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Coins entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCoinId());
 
        String shortName = entity.getShortName();
        if (shortName != null) {
            stmt.bindString(3, shortName);
        }
 
        String chongzhiAddress = entity.getChongzhiAddress();
        if (chongzhiAddress != null) {
            stmt.bindString(4, chongzhiAddress);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Coins readEntity(Cursor cursor, int offset) {
        Coins entity = new Coins( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // coinId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // shortName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // chongzhiAddress
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Coins entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCoinId(cursor.getInt(offset + 1));
        entity.setShortName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setChongzhiAddress(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Coins entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Coins entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Coins entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
